### ISSUE TITLE
Did't work when the python version is over than 3.7

### ISSUE THREAD

**Issue by barnett874** [billzt/PrimerServer2#10]
When I try run PrimerServer2 under python 3.8 or 3.9, it gives a error code:

**attributeerror: module 'primerserver2.core.global_var' has no attribute 'stop_run'**

I downgrade my python to 3.7 and reinstall again. It works properly.

Hope this will help to improve this awesome app.

cheers

**Comment by tao-bioinfo** [comment]
Sorry for my late response, but I don't know why the email notification in github doesn't work.

It should be work in python 3.8, but not in 3.9. I've updated the document and relevant version requirement in raw codes.

If issues still exist, can you print your env here? (a new Conda environment is better)

**Comment by imran-gh** [comment]
I'm also facing the same issue. Tried creating new conda environment also. This is my error

primertool full tests/query_design_multiple tests/example.fa
Designing Primers: 2 Finished (100%)|#################################################################################################################################################################|Time:  0:00:00
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/imran/miniconda3/envs/primer/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/imran/miniconda3/envs/primer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/primerserver2/core/design_primer.py", line 22, in single
    if global_var.stop_run is True:
AttributeError: module 'primerserver2.core.global_var' has no attribute 'stop_run'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/imran/miniconda3/envs/primer/bin/primertool", line 33, in <module>
    sys.exit(load_entry_point('primerserver2==2.0.0b21', 'console_scripts', 'primertool')())
  File "/Users/imran/miniconda3/envs/primer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/primerserver2/cmd/primertool.py", line 206, in main
    run(args)
  File "/Users/imran/miniconda3/envs/primer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/primerserver2/cmd/primertool.py", line 165, in run
    primers = design_primer.multiple(sites, cpu=args.cpu)
  File "/Users/imran/miniconda3/envs/primer/lib/python3.8/site-packages/primerserver2-2.0.0b21-py3.8.egg/primerserver2/core/design_primer.py", line 149, in multiple
    primers_in_each_site = result.get()
  File "/Users/imran/miniconda3/envs/primer/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: module 'primerserver2.core.global_var' has no attribute 'stop_run'

**Comment by tao-bioinfo** [comment]
Sorry for your inconvenience. I recommend using CRABS (https://github.com/gjeunen/reference_database_creator) instead. Although CRABS is designed for meta-barcoding, it can also be used in generic PCR.
